#!/bin/bash
#SBATCH -J GAUSS_OPENMP
#SBATCH --ntasks=8
#SBATCH --export=all
#SBATCH --out=./openmp_out_1-%j.out
#SBATCH --time=0-00:10:00
#SBATCH --mail-type=begin,end,fail,requeue

echo "openmp.c with 200"
./openmp.out 200 47

echo "--------------------------"

echo "openmp.c with 400"
./openmp.out 400 47

echo "--------------------------"

echo "openmp.c with 600"
./openmp.out 600  47


echo "--------------------------"

echo "openmp.c with 800"
./openmp.out 800  47


echo "--------------------------"

echo "openmp.c with 1000"
./openmp.out 1000  47


echo "--------------------------"

echo "openmp.c with 1200"
./openmp.out 1200  47


echo "--------------------------"

echo "openmp.c with 1400"
./openmp.out 1400  47

echo "--------------------------"

echo "openmp.c with 1600"
./openmp.out 1600  47

echo "--------------------------"

echo "openmp.c with 1800"
./openmp.out 1800  47

echo "--------------------------"

echo "openmp.c with 2000"
./openmp.out 2000  47

echo "--------------------------"

echo "openmp.c with 2200"
./openmp.out 2200  47

echo "--------------------------"

echo "openmp.c with 2400"
./openmp.out 2400  47

echo "--------------------------"

echo "openmp.c with 2600"
./openmp.out 2600  47

echo "--------------------------"

echo "openmp.c with 2800"
./openmp.out 2800  47

echo "--------------------------"

echo "openmp.c with 3000"
./openmp.out 3000  47